# Generated by Django 5.0.3 on 2024-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_clients',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
